#!/usr/bin/env bash
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
func()
{
printf "The subdomain %s is a " "$2"
dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{ printf $4 }'
printf " record and points to "
dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{ printf $5 }'
printf "\n"
}
if [ -z "$2" ]; then
for sub in "www" "lb-01" "web-01" "web-02"
do func "$1" "$sub"
done
else
func "$1" "$2"
fi
