#!/usr/bin/env bash
# Create a 404 error page
sudo apt-get update
sudo apt-get install -y nginx
sudo bash -c 'echo "Ceci n'\''est pas une page" > /var/www/html/custom_404.html'
err="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "25i $err" /etc/nginx/sites-available/default
sudo service nginx start
