#!/usr/bin/env bash
# Configure HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo bash -c 'echo "
frontend metoweb
    bind *:80
    mode http
    default_backend metoback
backend metoback
    balance roundrobin
    server 531000-web-01 54.173.91.227:80 check
    server 531000-web-02 3.85.1.149:80 check" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
