#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it
current_date=$(date +"%d-%m-%Y")
sudo mysqldump -u root -p "$1" –all-databases > backup.sql
tar -cvzf "$current_date".tar.gz backup.sql
