#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100 with fizzbuzz
for ((number=1;number<= 100;number++))
do
if ((number%5 == 0)) && ((number%3 == 0));then
echo "FizzBuzz"
elif ((number%5 == 0));then
echo "Buzz"
elif ((number%3 == 0));then
echo "Fizz"
else
echo "$number"
fi
done