#!/usr/bin/env bash
# Configuration of firewall
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
# Portforwarding using ufw
sudo sed -i 's.#net/ipv4/ip_forward=1.net/ipv4/ip_forward=1.' /etc/ufw/sysctl.conf
sudo bash -c  'echo "*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT" >> /etc/ufw/before.rules'
sudo ufw disable
sudo ufw enable
