#!/usr/bin/env bash
# Portforwarding using ufw
sudo sed -i 's.#net/ipv4/ip_forward=1.net/ipv4/ip_forward=1.' /etc/ufw/sysctl.conf
sudo bash -c  'echo "*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT" >> /etc/ufw/before.rules'
