#!/usr/bin/env bash
# creates an RSA key pair
# Name of the private key
KEY_NAME="school"

# Number of bits in the key
KEY_BITS=4096

# Passphrase for the key
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b ${KEY_BITS} -C ${KEY_NAME} -N ${PASSPHRASE} -f ${KEY_NAME}
